### ISSUE TITLE
Update to PostCSS 5.0.0

### ISSUE THREAD

**Issue by ai** [Pavliko/postcss-svg#13]
@Pavliko

**Comment by ai** [comment]
https://github.com/postcss/postcss/releases/tag/5.0.0

**Comment by ai** [comment]
Ping :)

**Comment by sc0rp10** [comment]
+1 @Pavliko

**Comment by pavel-gorlov** [comment]
Now I just updated version dependencies and version of the module. It's enough? Sorry for the stupid question 😳@ai

**Comment by ai** [comment]
@Pavliko also there are a API changes https://github.com/postcss/postcss/releases/tag/5.0.0

Like `eachDecl` → `walkDecls`

**Comment by ai** [comment]
Also please replace

``` js
console.info "postcss-svg: #{error}"
```

to

``` js
decl.warn(result, "postcss-svg: #{error}")
```

It is part of guidelines https://github.com/postcss/postcss/blob/master/docs/guidelines/plugin.md
