### ISSUE TITLE
Are we reusing the inline-svg here?

### ISSUE THREAD

**Issue by kamlekar** [Pavliko/postcss-svg#18]
This is a question. It seems the generated css is having the same svg many times with just the fill or stroke colors differently. 

I am thinking this is against the concept of reusability (that will definitely increase the css file size).

Please correct me if I am wrong.

**Comment by pavel-gorlov** [comment]
Yes, but after gzip compression increasing the size of the file will not be as significant.

**Comment by kamlekar** [comment]
Can't say.. 

What if I have a requirement where the icons color changes based on the selected themes. And there are lot of themes?

_I am not trying to argue with you but I think this is a not an optimized way of approaching the solution_

**Comment by cmnstmntmn** [comment]
@kamlekar in fact you will load a single `winter_theme.css` or `easter_theme.css`; you won't make use of both at the same time. 

so basicaly you have no redundancy over inline-svg code.

**Comment by kamlekar** [comment]
@cmnstmntmn that is fine for managing themes. but what if I have to change the same icon color to other colors on different actions like active, hover, disabled etc. ?

In such cases, here we are generating the same svg several times with different colors. My argument here is that this plugin is not reusing the SVG as we do by using inline SVG concept. and If I am right, my question is why we are doing so?

Please guide me.

**Comment by jonathantneal** [comment]
Inline SVG is an awesome Sassy option.

PostCSS SVG focuses on inlining the standard `url()` function, leveraging [SVG Parameters](https://tabatkins.github.io/specs/svg-params/) to let
you push compiled CSS variables into your SVGs, and [Modules](https://nodejs.org/api/modules.html#modules_modules) to let you reference the `media` or `main` fields from a `package.json`.

 [See example](https://github.com/Pavliko/postcss-svg#readme).
