### ISSUE TITLE
support for fragment identifier

### ISSUE THREAD

**Issue by maddesigns** [Pavliko/postcss-svg#22]
is it possible to support fragment identifiers for own SVG sprites?

this works for evil icons

```
  background-image: svg("ei#sc-github");
```

but not for other SVG sprites

**Comment by nishsinghal** [comment]
Seems to work but only if you first generate the full sprite file:

This doesn't work:

```
background: svg("sprite.svg#github");
```

This works:

```
background: svg("sprite.svg");
background: svg("sprite.svg#github");
```

Would be nice if there was a better way to do this as this will bloat up the CSS file considerably.

**Comment by dannybrown73** [comment]
I can't seem to get this to work with my own sprites as well...only evil icons. Double load trick above does not work either for some reason. Is there a particular type of sprite that we should use? Symbol, view, stacked...etc? Any help or examples of it working with your own sprites would be greatly appreciated.

**Comment by in-in** [comment]
@nishsinghal Not working for me also. 
Please share more details about your workaround. Which options you use?

**Comment by jonathantneal** [comment]
Fragment support is now in v2.
