### ISSUE TITLE
Url fill not replaced with given color

### ISSUE THREAD

**Issue by androdel** [Pavliko/postcss-svg#31]
If there is for example a gradient specified and called with a fill="url(...)", it does not get replaced with the color you've putted in.

**Comment by jonathantneal** [comment]
Use SVG Parametes for this. [See example](https://github.com/Pavliko/postcss-svg#readme)

**Comment by jhpratt** [comment]
@jonathantneal That doesn't help when you're trying to use SVGs provided by someone else. In my case, I'm using icons from Font Awesome (via npm), and I'm just looking for the ability to add a fill at build time.
