### ISSUE TITLE
Abandoned repository

### ISSUE THREAD

**Issue by sc0rp10** [Pavliko/postcss-svg#34]
Hi, @Pavliko 
Your plugin is really cool and used by many people in many projects. If plugin broke down, these people get problems (such as last epic problem with Chrome).
As I see, you can't support the project at a sufficient level. Maybe you can add another contributor with write access to this repo? Or maybe you can transfer repo + npm package to another gh user?
If you don't do it, plugin will be die in short time.

**Comment by sbstnmsch-zz** [comment]
This thingi should never die - too damn useful. Good job @Pavliko! Just add me and a few others if u need help.

**Comment by alexgorbatchev** [comment]
What are the Chrome issues? Also... fork the repo and carry on, it's pretty easy :)

**Comment by sc0rp10** [comment]
@alexgorbatchev you about #29? its fixed as I can see. Or is there any other Chrome-related issues?

**Comment by jonathantneal** [comment]
Just released v2!
