### ISSUE TITLE
How to write correct path to svg?

### ISSUE THREAD

**Issue by SVITY** [Pavliko/postcss-svg#36]
I have some independent react modules. For example http://take.ms/0VMBN
How to get path to svg into images folder in css? I tried relative path like './images/hdc.svg', but it does not work.

**Comment by SenerPhoenix** [comment]
don't write file name just write path.  ex : paths : ['./img/'] and in the CSS file call with file name and id like "test.svg#someid"

**Comment by jonathantneal** [comment]
You can write the paths with or without the starting `./`. Modules do not require you specify the `node_modules` directory. [See example](https://github.com/Pavliko/postcss-svg#readme)
